vuelidate/vuelidate

docs/assets/components/_inputs.sass, docs/partials/api/_values.pug, docs/partials/examples/ExampleAsync.vue, docs/partials/examples/_examples.pug, docs/partials/examples/index.js, docs/partials/validators/_validators.pug, package.json, src/index.js, src/validators/between.js, test/unit/index.js, test/unit/specs/validation.spec.js
=> Async validators

src/index.js, test/unit/specs/validation.spec.js
=> Validation for arrays of primitives

docs/partials/examples/ExampleDelayedTouch.vue, docs/partials/examples/_examples.pug, docs/partials/examples/index.js
Based on #38,
Requires #52 to be merged first
=> Add example of delayed $touch

docs/partials/validators/_validators.pug, src/validators/index.js, src/validators/numeric.js, test/unit/specs/validators/numeric.spec.js
=> Add numeric validator

src/validators/index.js
=> [#114] add url export

src/validators/common.js, test/unit/specs/validators/required.spec.js
This adds support for required boolean values, e.g. checkboxes.
=> Support boolean values in required validator

src/validators/common.js, test/unit/specs/validators/required.spec.js
=> Add date object support to required validator

src/index.js, test/unit/specs/regression/#144-dependency-crosstalk.spec.js
=> [#144] Avoid model dependency crosstalk

src/validators/macAddress.js, test/unit/specs/validators/macAddress.spec.js
=> Fix validator macAddress for EUI-48 address space

src/validators/common.js, test/unit/specs/validators/required.spec.js
No testing done
Patch for #156
=> Required validator now accepts false value as valid

docs/main.js, docs/partials/api/_values.pug, docs/partials/examples/ExampleAnyDirty.vue, docs/partials/examples/_examples.pug, docs/partials/examples/index.js, src/index.js, test/unit/specs/validation.spec.js
=> Implement and document $anyDirty and $anyError flag

docs/partials/validators/_validators.pug, src/validators/index.js
closes #193, #168, #260, #253, #240
=> Export validator helpers and improve documentation for custom validators

docs/partials/validators/_validators.pug, src/validators/index.js, src/validators/not.js, test/unit/specs/validators/not.spec.js
=> Implement not validator

docs/partials/api/_values.pug, src/index.js
=> Fix $anyError

packages/validators/src/raw/__tests__/requiredIf.spec.js, packages/validators/src/raw/requiredIf.js, packages/validators/src/raw/requiredUnless.js, packages/validators/src/utils/common.js
This PR should allow resolving props in the requiredIf and requireUnless validators.
Fixes #605
=> Аdd promise as property resolver to requireIf

packages/docs/src/.vuepress/components/AsObject.vue, packages/docs/src/.vuepress/components/NestedA.vue, packages/docs/src/.vuepress/components/NestedB.vue, packages/docs/src/.vuepress/components/NestedValidations.vue, packages/docs/src/.vuepress/enhanceApp.js, packages/vuelidate/src/core.js, yarn.lock
=> Add $touch and $reset to root.

packages/docs/src/README.md, packages/docs/src/guide.md
This PR builds upon the next documentation to provide a more guide style approach as suggested by @dobromir-hristov in #667
=> Next docs refactor

packages/test-project/main.js, packages/test-project/package.json, packages/test-project/src/App.vue, packages/test-project/src/components/OldApiExample.vue, packages/test-project/src/router.js, packages/test-project/src/routes.js, yarn.lock
Extracts the Vue router for the test project
=> feat: add vue-router

packages/test-project/src/components/DynamicValidations.vue, packages/validators/src/utils/common.js, packages/vuelidate/src/core.js, packages/vuelidate/src/index.js
=> Refactor validation results storage

README.md
Docs change
No Tests, it's a doc change for the next branch only.
Link is broken.
=> Update Next Docs Link

packages/validators/src/raw/__tests__/numeric.spec.js, packages/validators/src/raw/numeric.js
=> fix(validators): update "numeric" validator (fix #706)

packages/vuelidate/test/unit/specs/__snapshots__/validation.spec.js.snap, packages/vuelidate/test/unit/specs/validation.spec.js
=> test: add unit tests

packages/validators/index.d.ts, packages/validators/package.json, packages/vuelidate/index.d.ts, packages/vuelidate/package.json
Implements #723
I believe the typings cover all of vuelidate functionality except `$autoDirty`.
=> Official type definitions

packages/vuelidate/index.d.ts
=> fix #743 - VuelidatePlugin ts type to accept App argument

packages/vuelidate/src/core.js, packages/vuelidate/test/unit/specs/validation.spec.js
=> fix #744 pass path as parentKey to nested setValidations

packages/docs/src/custom_validators.md, packages/test-project/src/components/SimpleForm.vue
=> docs: custom error messages (fix #748)

packages/validators/src/withMessages/minLength.js, packages/validators/src/withMessages/sameAs.js
=> Improving validator message consistency

package.json, yarn.lock
I think this one was a typo but I might be wrong
=> chore: remove unused dep

packages/validators/index.d.ts
Forgotten question mark, I guess...
=> fix: declare second sameAs validator parameter as optional (#773)

packages/vuelidate/src/core.js, packages/vuelidate/test/unit/specs/validation.spec.js
Fixes the issues with `$autoDirty` when used as a root level config.
=> fix: autoDirty on root, closes #792

.github/workflows/run-unit-tests.yml, package.json, packages/vuelidate/package.json, packages/vuelidate/src/core.js, packages/vuelidate/src/index.js, packages/vuelidate/test/unit/specs/optionsApi.spec.js, packages/vuelidate/test/unit/specs/validation.spec.js, packages/vuelidate/test/unit/test-utils.js, packages/vuelidate/test/unit/utils.js, packages/vuelidate/test/unit/validations.fixture.js, scripts/swap-vue.js, yarn.lock
Enables testing Vue 2 and Vue 3 at the same time. Fixes issues with Vue 2. Closes #799 
None
=> fix(core): fix vue 2 issues, closes #799

packages/vuelidate/index.d.ts
Fixed the typings for `useVuelidate` to include the global config.
=> fix: Updated useVuelidate global config types

docs/partials/api/_methods.pug, docs/partials/api/_values.pug, docs/partials/validators/_validators.pug, src/vval.js
=> Fixed few spelling mistakes

README.md
=> Typo in Vuelidate Docs link.

packages/vuelidate/index.d.ts
=> Modify types to allow aync custom validator response

packages/vuelidate/index.d.ts
As discussed in the following PR https://github.com/vuelidate/vuelidate/pull/837 this should fix the introduced issues.
=> fix(core): fixed type issues regarding $externalResults

packages/docs/src/advanced_usage.md
**Other information:** I think you forgot to add the `.value` to the examples :)
=> Fix `clearExternalResults` example in docs

packages/docs/src/examples.md, packages/docs/src/guide.md, packages/validators/src/utils/common.js, packages/vuelidate/src/core.js, packages/vuelidate/src/index.js
A few simple grammatical tweaks for `it's` to `its` where appropriate. 
This is similar to #838 but targets the `next` branch.
=> docs: minor grammatical tweaks

packages/vuelidate/index.d.ts
=> fix(types): writable $model, closes vuelidate#892

packages/docs/src/.vitepress/config.js, packages/docs/src/advanced_usage.md, packages/docs/src/examples.md, packages/docs/src/guide.md, packages/docs/src/index.md
=> chore: update the docs

packages/validators/index.d.ts
This PR fixes misspelled parameter name for minLength validator.
=> chore(types): fix minLength param name

packages/docs/src/custom_validators.md
Hi super awesome Vuelidate people. I can't tell you how much I'm impressed by your work 🚀 
This PR fixes docs custom validators section code format. Tiny adjustment.
---
N/A
=> docs: remove unused import and fix code format

package.json, packages/validators/package.json, packages/vuelidate/package.json, yarn.lock
closes https://github.com/vuelidate/vuelidate/issues/963
=> fix: update vue-demi and composition-api to latest versions, fixes #963
