vuelidate/vuelidate

src/validators/email.js
src/validators/sameAs.js
test/unit/specs/validators/sameAs.spec.js

Fixes https://github.com/monterail/vuelidate/issues/65 and https://github.com/monterail/vuelidate/issues/66

email validator should return true for null, undefined and empty values

---

src/validators/alpha.js
src/validators/alphaNum.js
src/validators/numeric.js
test/unit/specs/validators/alpha.spec.js
test/unit/specs/validators/alphaNum.spec.js
test/unit/specs/validators/numeric.spec.js

required validator should be used for undefined, null and empty values.

Fix alpha, aplhaNum and numeric validators for undefined and null values

---

src/index.js
test/unit/specs/regression/#117-clean-error-evaluation.spec.js

Inverses access order in $error to prefer $dirty check first, which avoids a dependency on validation output.
Fixes #117

[#117] fix too eager validation evaluation on $error access

---

docs/partials/api/_methods.pug

See `$flattenParams` method name.

Increase cell size for better fit of methods name

---

docs/partials/validators/_validators.pug

Following up on issue #185, these changes - hopefully - clarify the use of the the *locator* meta parameter to configure the dynamic built-in validations.

Locator documentation improvement

---

src/index.js
test/unit/specs/validation.spec.js

https://jsfiddle.net/b5v4faqf/358/
It fails here: https://github.com/monterail/vuelidate/blob/master/src/index.js#L304
Since calling Object.keys on undefined or null throws.
```
TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at VueComponent.keys (node_modules\vuelidate\lib\index.js:351:23)
```
Haven't been able to clone and test your code locally yet due to some computer problems, but in my code this solution behaves as expected. So just relying on circleci to run the tests for me.

Allow setting array to undefined and null when using $each

---

src/index.js
test/unit/specs/validation.spec.js

Similar to https://github.com/monterail/vuelidate/pull/204 vuelidate fails when parent object is set to non object. Without this fix vuelidate will fail in the test I wrote, trying to access key from undefined.

Do not fail if parent object is non object

---

build/webpack.base.conf.js
package.json

This project does not currently build on a Windows environment as identified by @SirLamer in https://github.com/monterail/vuelidate/issues/136#issuecomment-298050082. These changes fix that.
- Add `cross-env` package to set environment variables, since `VAR=val` is invalid on Windows.
- Add `rimraf` package and use it instead of `rm -rf` which does not exist on Windows.
- Update the `exclude` path for eslint in `webpack.base.conf.js`, since Windows uses a different path delimiter.

Update build scripts to enable development on Windows

---

docs/partials/validators/_validators.pug
src/validators/decimal.js
src/validators/integer.js
src/validators/numeric.js
test/unit/specs/validators/decimal.spec.js
test/unit/specs/validators/integer.js
test/unit/specs/validators/integer.spec.js
test/unit/specs/validators/numeric.spec.js

As discussed in #136, numeric currently only accepts positive integer values. This pull request makes the following changes.
- Split numeric validator into numeric and integer validators.
- Update numeric validator to allow positive and negative decimal numbers.
- Limit integer validator to positive or negative whole numbers.
- Numeric validator still allows integers.
- Add unit tests for new validations.

Improve numeric validator

---

src/validators/index.js

Forgot to add `integer` and `decimal` to `index.js` in this previous pull request https://github.com/monterail/vuelidate/pull/245

Add integer and decimal validators to index.js

---

.babelrc

this fixed #301 for me
the `env` condition in the `.babelrc` was never met, see [babel env option](https://babeljs.io/docs/usage/babelrc/#env-option)

fix #301 - broken imports in node environment

---

docs/partials/examples/_examples.pug

The current documentation doesn't make it very clear that errors will show on initial load, and that the example given relies on custom CSS to hide error messages.

Update _examples.pug to clarify error visibility

---

packages/vuelidate/src/core.js
packages/vuelidate/src/index.js

Extracts core related login into `core.js` leaving bootstrapping logic to sit into `index.html`.
Adds some jsdoc comments and types, would be later used for TS.

Reorganize vuelidate core and add jsdoc types

---

packages/docs/README.md
packages/docs/src/.vuepress/config.js
packages/docs/src/README.md
packages/docs/src/advanced_usage.md
packages/docs/src/api.md
packages/docs/src/custom_validators.md
packages/docs/src/examples.md
packages/docs/src/guide.md

This PR updates the Vuelidate Next docs, to a more guide oriented approach, where we teach the users how to use Vuelidate, compared to before, where we just threw some APIs and examples at them.
This should ensure an easier introduction, while still keeping the API and Examples pages, for more advanced users.
This is ofc a very very early draft, many things are yet to be done.
One thing we need to figure out is examples. In Vuelidate 0.x they were real live components, that you could interact with, hosted with the docs files.
We cant really do this now, as Vuepress runs vue 2, and the code uses vue 3
**We can:** 
1. Migrate over to Vitepress (too early imho)
2. Wait it out for now.
3. Just add static example code
4. Use a plugin, like https://github.com/QingWei-Li/vuep but more …

Update Next docs

---

packages/vuelidate/src/core.js
packages/vuelidate/test/unit/specs/validation.spec.js
packages/vuelidate/test/unit/validations.fixture.js

**Description:**
~~1. Using the mixin, I found out that `validations` was passed to `setValidations` as a reference. It was problematic. Suppose I wrote:~~
```js
defineComponent({
validations: {
foo: {
required
}
}
});
```
~~Vuelidate interpreted it without unwrapping it first, as if I had written:~~
```js
defineComponent({
validations: {
value: {
foo: {
required
}
}
}
});
```
~~This patch unwraps `validations`.~~
This first part is already fixed by @shentao in 5725a38da12848fc699c719dafa06706107f0374
2. Refs of nested objects lose reactivity …

fix: chain of state refs

---

packages/validators/src/withMessages/minLength.js

If you have used the minLength validator with vuelidate 1.0, the format is the same.
If you've used the minLength validator in @vuelidate/validators v<=2.0.0-alpha.2 you may need to update your templates from "$v.name.minLength.$params.length" to "$v.name.minLength.$params.min"

Unify minLength validator format

---

packages/vuelidate/index.d.ts

---
This was broken in https://github.com/vuelidate/vuelidate/pull/745 and should be fixed now

Fix: changed type for VuelidatePlugin to Plugin from vue

---

packages/validators/src/utils/withMessage.js

The current implementation of `withMessage` modifies the validator that is passed as an argument, so that each previous invocation of `withMessage` returns the same message that was used in the final call to `withMessage`. This pull request modifies the helper method so that it returns a copy of the validator with the proper message.

fix: remove side effects from withMessage helper (#763)

---

package.json
packages/docs/src/advanced_usage.md
packages/docs/src/api.md
packages/vuelidate/src/index.js
packages/vuelidate/test/unit/specs/validation.spec.js
packages/vuelidate/test/unit/validations.fixture.js
yarn.lock

This PR allows adding a scope to your validations, limiting the parent/child collection of validation results.
1. Parent collects all by default.
2. Child can specify it does not want to be collected.
3. If parent and child scope is the same, validations get collected.
4. If parent is set to collect all, child scope does not matter.
The `$scope` global property allows closely connecting component forms.
```js
const Child = {
name: 'child',
setup() {
return { v: …
```

feat: allow scoping of component validations, fixes: #719

---

packages/docs/src/.vitepress/config.js
packages/docs/src/.vitepress/theme/components/AsComposition.vue
packages/docs/src/examples.md
packages/test-project/src/components/SimpleForm.vue
packages/validators/src/common.js
packages/validators/src/utils/__tests__/common.spec.js
packages/validators/src/utils/common.js
packages/vuelidate/src/core.js
packages/vuelidate/src/storage.js
packages/vuelidate/test/unit/specs/optionsApi.spec.js
packages/vuelidate/test/unit/specs/validation.spec.js
packages/vuelidate/test/unit/utils.js
packages/vuelidate/test/unit/validations.fixture.js
packages/vuelidate/test/unit/validators.fixture.js

Make validators async by default. No need to wrap validators in `withAsync`, they can just return a Promise.

refactor: all validators are async by default, removes withAsync helper

---

packages/docs/package.json
packages/docs/src/advanced_usage.md
packages/vuelidate/src/core.js
packages/vuelidate/test/unit/specs/validation.spec.js
yarn.lock

This PR renames the `$invalid` property on rich validation responses to `$valid` to better reflect it's value.
BREAKING CHANGE: It used to be `$invalid`, but that did not make any sense, as the return value was identical to boolean validators.

refactor: rename $invalid response property to $valid

---

packages/validators/src/utils/common.js
packages/vuelidate/index.d.ts

Replaces forgotten occurrences of `$invalid` for rich validation responses with the new `$valid` property.

fix/replace $invalid with $valid

---

packages/vuelidate/src/index.js
packages/vuelidate/test/unit/specs/validation.spec.js
packages/vuelidate/test/unit/utils.js

Allows using Vuelidate outside of Vue Components. No breaking changes or API changes.

feat: allow usage outside Vue components

---

packages/vuelidate/src/core.js
packages/vuelidate/test/unit/specs/validation.spec.js

Arrays and objects were not being deeply watched, so this should fix that. closes #832 

fix: watch changes to arrays and objects deeply, closes #832

---

packages/docs/src/.vitepress/config.js
packages/docs/src/advanced_usage.md
packages/docs/src/api/error_object.md
packages/docs/src/guide.md
packages/docs/src/index.md
packages/docs/src/migration_guide.md
packages/vuelidate/index.d.ts
packages/vuelidate/src/core.js
packages/vuelidate/test/unit/specs/__snapshots__/validation.spec.js.snap
packages/vuelidate/test/unit/specs/optionsApi.spec.js
packages/vuelidate/test/unit/specs/validation.spec.js
packages/vuelidate/test/unit/utils.js

This PR adds a `$uid` property to allow for proper `key` usage when iterating over error messages, closes #843 

feat(core): adds an $uid property to the $errors objects, fix #843 

---

packages/validators/src/raw/__tests__/and.spec.js
packages/validators/src/raw/__tests__/not.spec.js
packages/validators/src/raw/__tests__/requiredIf.spec.js
packages/validators/src/raw/__tests__/requiredUnless.spec.js
packages/validators/src/raw/and.js
packages/validators/src/raw/not.js
packages/validators/src/raw/requiredIf.js
packages/validators/src/raw/requiredUnless.js

This PR fixes an issue I introduced a while back when refactoring the validators. fixes #831
`this` context should now be properly passed to `requiredIf` and friends.

fix(validators): properly pass `this` context to complex validators, closes #831

---

packages/docs/src/custom_validators.md
packages/docs/src/migration_guide.md
packages/test-project/src/components/SimpleForm.vue
packages/validators/src/common.js
packages/validators/src/utils/__tests__/withAsync.spec.js
packages/validators/src/utils/__tests__/withMessage.spec.js
packages/validators/src/utils/__tests__/withParams.spec.js
packages/validators/src/utils/common.js
packages/validators/src/utils/withAsync.js
packages/validators/src/utils/withMessage.js
packages/validators/src/utils/withParams.js
packages/vuelidate/src/core.js
packages/vuelidate/test/unit/specs/optionsApi.spec.js
packages/vuelidate/test/unit/specs/validation.spec.js
packages/vuelidate/test/unit/validations.fixture.js
packages/vuelidate/test/unit/validators.fixture.js
yarn.lock

Reverts back to using `computed` and `withAsync` for async validators.
It adds an extra `watchTargets` featured as a second parameter to `withAsync`. This allows you to provide extra watch targets, when using an async validator, that depends on other reactive properties.

revert(core): return back to using computed and withAsync

---

packages/validators/src/withMessages/alpha.js
packages/validators/src/withMessages/alphaNum.js
packages/validators/src/withMessages/and.js
packages/validators/src/withMessages/between.js
packages/validators/src/withMessages/decimal.js
packages/validators/src/withMessages/email.js
packages/validators/src/withMessages/integer.js
packages/validators/src/withMessages/ipAddress.js
packages/validators/src/withMessages/macAddress.js
packages/validators/src/withMessages/maxLength.js
packages/validators/src/withMessages/maxValue.js
packages/validators/src/withMessages/minLength.js
packages/validators/src/withMessages/minValue.js
packages/validators/src/withMessages/not.js
packages/validators/src/withMessages/numeric.js
packages/validators/src/withMessages/or.js
packages/validators/src/withMessages/required.js
packages/validators/src/withMessages/requiredIf.js
packages/validators/src/withMessages/requiredUnless.js
packages/validators/src/withMessages/sameAs.js
packages/validators/src/withMessages/url.js

1. Adds `type` to all validator `$params`, so we dont break more complex cases, from Vuelidate 0.x, which provided those.
2. Passes the value for `requiredIf` and `requiredUnless` as a `$param`. This fixes issues with those validators not updating.

feat(validators): add type param to validators, closes #657, #856, #866

---

packages/docs/src/advanced_usage.md
packages/docs/src/api/methods.md
packages/vuelidate/index.d.ts
packages/vuelidate/src/core.js
packages/vuelidate/src/index.js
packages/vuelidate/src/utils.js
packages/vuelidate/test/unit/specs/optionsApi.spec.js
packages/vuelidate/test/unit/specs/validation.spec.js
packages/vuelidate/test/unit/test-utils.js

Adds external validator support to Vuelidate. For each state property, we can have a validation error from the server. It can be a single string or even an array of errors. closes #824 
```
const state = {
child: 'a',
nested: {
nestedChild: 'b'
}
}
const externalErrors = {
child: 'Child is not Valid',
nested: {
nestedChild: ['Foo', 'bar']
}
}
```
This adds a `$externalResults` key to the Vuelidate validation object as well as triggers both `$invalid` and `$error` if said property external results are not empty.
```js
const state = {
number: 0
}
const $externalResults = ref({});
const v = useVuelidate(rules, state, { $externalResults })
async function addExternalErrors(){
$externalResults.value = { number: 'Must be above 0' }
}
```
If you need to have external results, just create a …

feat(core): add external validations support

---

packages/docs/src/advanced_usage.md
packages/test-project/main.js
packages/test-project/package.json
packages/test-project/src/App.vue
packages/test-project/src/components/I18nSimpleForm.vue
packages/test-project/src/i18n.js
packages/test-project/src/routes.js
packages/vuelidate/src/core.js
packages/vuelidate/test/unit/specs/validation.spec.js
yarn.lock

This PR adds a few extra properties to the `$message` function parameters, so its super easy to create simple and reusable translations on the client side. closes #769
We could probably have our own layer on top of `$message`, that ships with all messages in a file or something, so its easy for users to just provide their own instance of `$t` but I think the solution I provided in the docs is fine as is.

feature(core): pass more parameters to `$message` to help with i18n support

---

packages/validators/index.d.ts

The motivation for this PR is only type-wise and not runtime wise.
Actual problem: When using `withParams` or `withMessage`, the validator function `ValidatorFn` param is always `unknown`. Which I understand because it enforces type guards to type check runtime values too.
But there is some validators where we are *sure* what type the validator value will have.
With casting support, both this validators will be valid for Typescript. Actual version: Error
```ts
export const minSize = …
```

Added TS cast support for withParams and withMessage

---

packages/vuelidate/index.d.ts

If provided, the reactivity of `$externalResults` already works correctly if a `Ref<ServerErrors>`  is passed. However it's currently not allowed by the typescript definition.

fix(types): allow reactive ServerErrors in GlobalConfig

---

packages/components/package.json
packages/validators/package.json
packages/vuelidate/package.json

> If the package.json for your package is not in the root directory (for example if it is part of a monorepo), you can specify the directory in which it lives:
> ```json
> "repository": {
>   "type" : "git",
>   "url" : "https://github.com/facebook/react.git",
>   "directory": "packages/react-dom"
> }
> ```
> — https://docs.npmjs.com/cli/v6/configuring-npm/package-json#repository
I use a lot https://njt.vercel.app/ to jump to different packages information,
and with this PR we can know exactly what package in what folder lives
Made the changes with a script to make it easier 🙂
https://gist.github.com/iamandrewluca/5cc85b56a595056f0099d04ed6dd8a79

chore: add repository for all packages.json

---

packages/components/.browserslistrc
packages/vuelidate/.browserslistrc

Fixes #895 by removing IE as a build target, drastically reducing transpilation

build: reduce transpilation, by removing IE target entirely, fix #895

---

packages/vuelidate/src/core.js
packages/vuelidate/test/unit/specs/optionsApi.spec.js
packages/vuelidate/test/unit/specs/validation.spec.js

Sets $error to `true`, if a validator is `pending`, but does not show error messages for said field. fixes #875 
1. A field will still have `$error==true`, while the validator is resolving.
2. A field is considered under error, if any of its child validators are still pending.
3. If you dont debounce async validators, new invocations while previous ones resolve, will reset the `invalid` state to `false`.

fix: change async validators to return invalid, only after they resolve, fixes #875

---

packages/docs/src/advanced_usage.md
packages/test-project/src/App.vue
packages/test-project/src/components/ExternalValidationsForm.vue
packages/test-project/src/routes.js
packages/vuelidate/src/core.js
packages/vuelidate/test/unit/specs/optionsApi.spec.js
packages/vuelidate/test/unit/specs/validation.spec.js
packages/vuelidate/test/unit/utils.js
scripts/swap-vue.js

Automatically resets the `$externalResults` key for a changed property, when using `$autoDirty` or `$model`. closes #891 
This should make the `$clearExternalResults` method unnecessary, as the user would probably update the field before submitting again.

fix(core): reset the $externalResults key for a changed property, closes #891

---

.eslintrc.js
packages/vuelidate/index.d.ts
packages/vuelidate/src/core.js
packages/vuelidate/src/index.js
packages/vuelidate/test/unit/specs/validation.spec.js

Adds the `$validate` method to every validation leaf, in order to allow for validation per form.
Closes #861

feat(core): add the $validate method to every validation leaf, closes #861

---

packages/validators/src/utils/__tests__/forEach.spec.js
packages/validators/src/utils/forEach.js

Stops the forEach helper from throwing when there is no validator for a single property in the state it observes. closes #931 

fix: forEach helper throwing, when state has no validator, closes #931 

---

packages/vuelidate/index.d.ts

**Reason**
There's no simple way how to use predefined  configuration of Vuelidate. By exporting selected types, man can use them if needed.

fix(types): export types, closes #849

---

packages/validators/index.d.ts
packages/vuelidate/index.d.ts

I do not expect this to be a breaking change for TypeScript users but I think that there is still room for improvement.
This is a fork of #903 which appears to resolve #917 with the changes discussed in the original PR's comments. The goal of this modded version of the original PR is to unblock teams like mine that need typed `vm` and are unable to use explicitly typed `ValidatorFn`.
I still have not figured out a good dev setup for this library so I unfortunately …

Types for or/not/and, `ValidatorFn`, relax types (PR #903 + mods)

---

packages/test-project/src/App.vue
packages/test-project/src/components/NestedValidationsWithScopes/ChildWithScope.vue
packages/test-project/src/components/NestedValidationsWithScopes/ParentValidator.vue
packages/test-project/src/routes.js
packages/vuelidate/src/index.js
packages/vuelidate/test/unit/specs/validation.spec.js

This PR fixes a bug where multiple Vuelidate instances from the same component did not collect the children instances. Fixes #960 
1. run `yarn install` on the root of the package
2. Go to the `test-project` package
3. run `yarn run dev`
4. Go to http://localhost:3000/nested-validations-with-scopes
5. Toggle the child on/off and toggle the output.

fix(core): allow providing child results into multiple Vuelidate instances

---

packages/docs/src/custom_validators.md

If my understanding is correct, these should be typos.

docs: fix typos in `custom_validators.md`

---

README.md

Fix incorrect vuelidate instance naming (v$ vs $v)

---

packages/validators/index.d.ts

I didn't know how to test the changes other than to create a file, composing all validators with the createI18nMessage function and checking that no typescript error is thrown. The function `notValidator` was added as a reference and should throw an error of course.

fix typing for createI18nMessage (fix #972)
